[package]
name = "xline"
version = "0.1.0"
edition = "2021"
authors = ["DatenLord <dev@datenlord.io>"]
description = "Distributed KV storage for metadata"
repository = "https://github.com/datenlord/Xline"
readme = "README.md"
license = "Apache-2.0"
keywords = ["KV", "consistency", "metadata"]
categories = ["KV"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
clap = { version = "3.2.16", features = ["derive"] }
clippy-utilities = "0.2.0"
curp = { path = "../curp" }
env_logger = "0.9.0"
itertools = "0.10.3"
log = "0.4.17"
parking_lot = "0.12.0"
prost = "0.11.0"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.0", features = [
    "rt-multi-thread",
    "time",
    "fs",
    "macros",
    "net",
] }
tokio-stream = { version = "0.1.9", features = ["net"] }
tonic = "0.8.0"
uuid = { version = "1.1.2", features = ["v4"] }


[build-dependencies]
tonic-build = "0.8.0"

[dev-dependencies]
etcd-client = "0.9.2"
